name: deepresearch
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=5_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py311h0281608_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.14=h5eee18b_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.9.1=hac33072_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py311hee96239_0
  - asgiref=3.10.0=pyhd8ed1ab_0
  - asttokens=3.0.0=py311h06a4308_0
  - async-lru=2.0.5=py311h06a4308_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h48c9088_3
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.6=h82d11aa_3
  - aws-c-http=0.10.4=h94feff3_3
  - aws-c-io=0.22.0=h57f3b0d_1
  - aws-c-mqtt=0.13.3=h2b1cf8c_6
  - aws-c-s3=0.8.6=h4e5ac4b_5
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.34.4=h60c762c_0
  - aws-sdk-cpp=1.11.606=h32384e2_4
  - azure-core-cpp=1.16.0=h3a458e0_1
  - azure-identity-cpp=1.12.0=ha729027_0
  - azure-storage-blobs-cpp=12.14.0=hb1c9500_1
  - azure-storage-common-cpp=12.10.0=hebae86a_2
  - azure-storage-files-datalake-cpp=12.12.0=h8b27e44_3
  - babel=2.16.0=py311h06a4308_0
  - backoff=2.2.1=pyhd8ed1ab_1
  - bcrypt=5.0.0=py311h902ca64_1
  - beautifulsoup4=4.13.5=py311h06a4308_0
  - bleach=6.2.0=py311h06a4308_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.1.0=py311h1ddb823_4
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cachetools=6.2.1=pyhd8ed1ab_0
  - cairo=1.18.0=hbb29018_2
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - chromadb=1.0.20=py311h4150861_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - comm=0.2.1=py311h06a4308_0
  - contourpy=1.3.1=py311hdb19cb5_0
  - cpython=3.11.14=py311hd8ed1ab_2
  - cryptography=46.0.3=py311h8488d03_0
  - cuda-crt-tools=12.9.86=ha770c72_2
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hffce074_1
  - cuda-cupti=12.9.79=h676940d_1
  - cuda-nvcc-tools=12.9.86=he02047a_2
  - cuda-nvdisasm=12.9.88=hffce074_1
  - cuda-nvrtc=12.9.86=hecca717_1
  - cuda-nvtx=12.9.79=hecca717_1
  - cuda-nvvm-tools=12.9.86=h4bc722e_2
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.1.4=hbcb9cd8_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=4.4.1=pyhcf101f3_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.8.16=py311hbdd6827_1
  - decorator=5.2.1=py311h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - dnspython=2.8.0=pyhcf101f3_0
  - double-conversion=3.3.1=h6a678d5_0
  - durationpy=0.10=pyhd8ed1ab_0
  - email-validator=2.3.0=pyhd8ed1ab_0
  - email_validator=2.3.0=hd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=py311h06a4308_0
  - expat=2.7.3=h3385a95_0
  - fastapi=0.115.9=pyh29332c3_0
  - fastapi-cli=0.0.13=pyhcf101f3_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.60.1=py311hee96239_0
  - freetype=2.14.1=ha770c72_0
  - frozenlist=1.7.0=py311h52bc045_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h92a432a_1
  - google-auth=2.43.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - graphite2=1.3.14=h295c915_1
  - grpcio=1.73.1=py311h46a3a17_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hf-xet=1.2.0=py310hb823017_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httptools=0.7.1=py311h49ec1c0_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh707e725_8
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_metadata=8.7.0=h40b2b14_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.30.1=py311h06a4308_0
  - ipynbname=2023.2.0.0=pyhd8ed1ab_0
  - ipython=9.5.0=py311h06a4308_0
  - ipython_pygments_lexers=1.1.1=py311h06a4308_0
  - ipywidgets=8.1.7=py311h06a4308_0
  - jedi=0.19.2=py311h06a4308_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.9.25=py311h06a4308_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter=1.1.1=py311h06a4308_0
  - jupyter-lsp=2.2.5=py311h06a4308_0
  - jupyter_client=8.6.3=py311h06a4308_0
  - jupyter_console=6.6.3=py311h06a4308_0
  - jupyter_core=5.8.1=py311h06a4308_0
  - jupyter_events=0.12.0=py311h06a4308_0
  - jupyter_server=2.16.0=py311h06a4308_0
  - jupyter_server_terminals=0.5.3=py311h06a4308_0
  - jupyterlab=4.4.7=py311h06a4308_0
  - jupyterlab_pygments=0.3.0=py311h06a4308_0
  - jupyterlab_server=2.28.0=py311h06a4308_0
  - jupyterlab_widgets=3.0.15=py311h06a4308_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.8=py311h6a678d5_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=21.0.0=h56a6dad_8_cpu
  - libarrow-acero=21.0.0=h635bf11_8_cpu
  - libarrow-compute=21.0.0=h8c2c5c3_8_cpu
  - libarrow-dataset=21.0.0=h635bf11_8_cpu
  - libarrow-substrait=21.0.0=h3f74fd7_8_cpu
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=38_h5875eb1_mkl
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=38_hfef963f_mkl
  - libclang-cpp18.1=18.1.8=default_h99862b1_15
  - libclang13=20.1.8=default_hee3e7a4_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.9.1.4=h676940d_1
  - libcudnn=9.10.1.4=hf7e9902_1
  - libcudnn-dev=9.10.1.4=h58dd1b1_1
  - libcudss=0.7.1.4=h58dd1b1_0
  - libcufft=11.4.1.4=hecca717_1
  - libcufile=1.14.1.1=hbc026e6_1
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.10.19=h676940d_1
  - libcurl=8.17.0=h4e3cde8_0
  - libcusolver=11.7.5.82=h676940d_2
  - libcusparse=12.5.10.65=hecca717_2
  - libde265=1.0.15=h00ab1b0_0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.80.2=hf974151_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libheif=1.19.7=gpl_hc18d805_100
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=38_h5e43f62_mkl
  - libllvm18=18.1.8=default_hddf928d_9
  - libllvm20=20.1.8=hecd9e04_0
  - libmagma=2.9.0=ha7672b3_3
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=12.9.86=hecca717_2
  - libnvjpeg=12.4.0.76=hecca717_1
  - libopengl=1.7.0=h5eee18b_2
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=21.0.0=h790f06f_8_cpu
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h421ea60_1
  - libpq=16.10=h1cdf469_2
  - libprotobuf=6.31.1=h49aed37_2
  - libpulsar=3.7.2=hfb58281_1
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsentencepiece=0.2.1=h022d5ca_0
  - libsodium=1.0.20=heac8642_0
  - libsqlite=3.51.0=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsystemd0=258.2=h07e904d_0
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.0=he137b08_1
  - libtorch=2.8.0=cuda129_mkl_hf53477d_302
  - libudev1=258.2=h07e904d_0
  - libutf8proc=2.11.0=hb04c3b8_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libxslt=1.1.43=h28b3bda_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=21.1.5=h4922eb0_0
  - lz4-c=1.10.0=h5888daf_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py311h3778330_0
  - matplotlib=3.10.7=py311h38be061_0
  - matplotlib-base=3.10.7=py311h0f3be63_0
  - matplotlib-inline=0.1.7=py311h06a4308_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.2=py311h06a4308_0
  - mkl=2025.3.0=h0e700b2_462
  - mmh3=5.2.0=py311h1ddb823_2
  - monotonic=1.6=pyhd8ed1ab_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.6.3=py311h2dc5d0c_0
  - multiprocess=0.70.18=py311haee01d2_2
  - mysql-common=8.3.0=h70512c7_5
  - mysql-libs=8.3.0=ha479ceb_5
  - nbclient=0.10.2=py311h06a4308_0
  - nbconvert=7.16.6=py311h06a4308_0
  - nbconvert-core=7.16.6=py311h06a4308_0
  - nbconvert-pandoc=7.16.6=py311h06a4308_0
  - nbformat=5.10.4=py311h06a4308_0
  - nccl=2.28.7.1=h4d09622_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py311h06a4308_0
  - networkx=3.5=pyhe01879c_0
  - nlohmann_json=3.12.0=h54a6638_1
  - nltk=3.9.2=pyhcf101f3_1
  - notebook=7.4.5=py311h06a4308_0
  - notebook-shim=0.2.4=py311h06a4308_0
  - numpy=2.3.4=py311h2e04523_0
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - ollama-python=0.6.0=pyhd8ed1ab_0
  - onnxruntime=1.22.0=py311h4107d7c_200_cuda
  - openjpeg=2.5.3=h55fea9a_1
  - openssl=3.5.4=h26f9b46_0
  - opentelemetry-api=1.38.0=pyhd8ed1ab_0
  - opentelemetry-exporter-otlp-proto-common=1.38.0=pyhd8ed1ab_0
  - opentelemetry-exporter-otlp-proto-grpc=1.38.0=pyhd8ed1ab_0
  - opentelemetry-instrumentation=0.59b0=pyhd8ed1ab_0
  - opentelemetry-instrumentation-asgi=0.59b0=pyhd8ed1ab_0
  - opentelemetry-instrumentation-fastapi=0.59b0=pyhd8ed1ab_0
  - opentelemetry-proto=1.38.0=pyhd8ed1ab_0
  - opentelemetry-sdk=1.38.0=pyhd8ed1ab_0
  - opentelemetry-semantic-conventions=0.59b0=pyh3cfb1c2_0
  - opentelemetry-util-http=0.59b0=pyhd8ed1ab_0
  - optree=0.17.0=py311hdf67eae_2
  - orc=2.2.1=hd747db4_0
  - orjson=3.11.4=py311h902ca64_0
  - outcome=1.3.0.post0=pyhd8ed1ab_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hed34c8f_1
  - pandoc=3.8=h06a4308_0
  - pandocfilters=1.5.1=py311h06a4308_0
  - parso=0.8.4=py311h06a4308_0
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.9.0=py311h06a4308_1
  - pillow=11.3.0=py311h98278a2_3
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=py311h06a4308_0
  - posthog=5.4.0=pyhd8ed1ab_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prometheus_client=0.21.1=py311h06a4308_0
  - prompt-toolkit=3.0.52=py311h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.3.1=py311h2dc5d0c_0
  - protobuf=6.31.1=py311h425ed32_2
  - psutil=7.0.0=py311hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pulsar-client=3.8.0=py311h0720a22_1
  - pure_eval=0.2.3=py311h06a4308_0
  - pyarrow=21.0.0=py311h38be061_1
  - pyarrow-core=21.0.0=py311h342b5a4_1_cpu
  - pyasn1=0.6.1=pyhd8ed1ab_2
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pybase64=1.4.2=py311h49ec1c0_1
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.2.0=py311h06a4308_0
  - pypdf=6.2.0=pyhcf101f3_0
  - pypdf2=3.0.1=pyhd8ed1ab_1
  - pypika=0.48.9=pyhd8ed1ab_1
  - pyproject_hooks=1.2.0=pyhd8ed1ab_1
  - pyside6=6.7.2=py311h9053184_4
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h6fa692b_0
  - python-build=1.3.0=pyhff2d567_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-fastjsonschema=2.20.0=py311h06a4308_0
  - python-flatbuffers=25.9.23=pyh1e1bc0e_0
  - python-gil=3.11.14=hd8ed1ab_2
  - python-json-logger=3.2.1=py311h06a4308_0
  - python-kubernetes=33.1.0=pyhd8ed1ab_0
  - python-multipart=0.0.20=pyhff2d567_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py311h041eb40_1
  - python_abi=3.11=2_cp311
  - pytorch=2.8.0=cuda129_mkl_py311_h974e97e_302
  - pytorch-gpu=2.8.0=cuda129_mkl_h43a4b0b_302
  - pytz=2025.2=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - pyyaml=6.0.3=py311h3778330_0
  - pyzmq=27.1.0=py311hcf8288c_1
  - qhull=2020.2=hdb19cb5_2
  - qt6-main=6.7.2=h7d13b96_3
  - qtconsole=5.7.0=py311h06a4308_0
  - qtpy=2.4.3=py311h06a4308_0
  - rav1e=0.7.1=h8fae777_3
  - rdma-core=60.0=hecca717_0
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2025.11.3=py311h49ec1c0_1
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-toolkit=0.15.1=pyhcf101f3_0
  - rpds-py=0.28.0=py311h902ca64_1
  - rsa=4.9.1=pyhd8ed1ab_0
  - s2n=1.5.26=h5ac9029_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - safetensors=0.6.2=py311hc8fb587_1
  - scikit-learn=1.7.2=py311hc3e1efb_0
  - scipy=1.16.3=py311h1e13796_0
  - seaborn=0.13.2=py311h06a4308_3
  - selenium=4.38.0=pyhcf101f3_0
  - selenium-manager=4.38.0=hb17b654_0
  - send2trash=1.8.2=py311h06a4308_1
  - sentence-transformers=3.0.1=pyhd8ed1ab_0
  - sentencepiece=0.2.1=h074ec65_0
  - sentencepiece-python=0.2.1=py311hb489893_0
  - sentencepiece-spm=0.2.1=h022d5ca_0
  - setuptools=80.9.0=py311h06a4308_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - snappy=1.2.2=h03e3b7b_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.5=py311h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=py311h06a4308_0
  - starlette=0.45.3=pyha770c72_0
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=h8d10470_1
  - tenacity=9.1.2=pyhd8ed1ab_0
  - terminado=0.18.1=py311h06a4308_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tiktoken=0.12.0=py311h9a14573_1
  - tinycss2=1.4.0=py311h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.3.0=pyhcf101f3_0
  - torchvision=0.24.0=cuda129_py311_had7ad20_2
  - torchvision-extra-decoders=0.0.2=py311hfbc2085_4
  - tornado=6.5.1=py311h5eee18b_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py311h06a4308_0
  - trio=0.32.0=py311h3d13dd8_1
  - trio-websocket=0.12.2=pyh29332c3_0
  - triton=3.4.0=cuda129py311h2e1fb5d_1
  - typer=0.20.0=pyhdb1f59b_0
  - typer-slim=0.20.0=pyhcf101f3_0
  - typer-slim-standard=0.20.0=h65a100f_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - uvicorn=0.38.0=pyh31011fe_0
  - uvicorn-standard=0.38.0=h31011fe_0
  - uvloop=0.22.1=py311h49ec1c0_1
  - watchfiles=1.1.1=py311hc8fb587_0
  - wayland=1.24.0=hdac8c69_0
  - wcwidth=0.2.13=py311h06a4308_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - websockets=15.0.1=py311haee01d2_2
  - wheel=0.45.1=py311h06a4308_0
  - widgetsnbextension=4.0.14=py311h06a4308_0
  - wrapt=1.17.3=py311h49ec1c0_1
  - wsproto=1.2.0=pyhd8ed1ab_1
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.3=hb47aa4a_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py311h3778330_0
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.25.0=py311haee01d2_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - accelerate==1.11.0
      - aiofiles==24.1.0
      - aioitertools==0.13.0
      - aiosqlite==0.21.0
      - alembic==1.17.1
      - arize-phoenix==12.12.0
      - arize-phoenix-client==1.22.0
      - arize-phoenix-evals==2.5.0
      - arize-phoenix-otel==0.13.1
      - authlib==1.6.5
      - boto3==1.40.70
      - botocore==1.40.70
      - bracex==2.6
      - cbor2==5.7.1
      - ddgs==9.9.0
      - docker==7.1.0
      - dockerfile-parse==2.0.1
      - e2b==2.6.4
      - e2b-code-interpreter==2.3.0
      - fastuuid==0.14.0
      - ffmpy==0.6.4
      - gradio==5.49.1
      - gradio-client==1.13.3
      - graphql-core==3.2.7
      - greenlet==3.2.4
      - groovy==0.1.2
      - grpc-interceptor==0.15.4
      - grpclib==0.4.8
      - helium==5.1.2
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - jiter==0.12.0
      - jmespath==1.0.1
      - jsonpath-ng==1.7.0
      - jsonref==1.1.0
      - litellm==1.79.3
      - lxml==6.0.2
      - mako==1.3.10
      - markdownify==1.2.0
      - mcp==1.21.0
      - mcpadapt==0.1.19
      - mlx-lm==0.28.3
      - modal==1.2.2
      - openai==2.7.2
      - openinference-instrumentation==0.1.42
      - openinference-instrumentation-smolagents==0.1.19
      - openinference-semantic-conventions==0.1.25
      - opentelemetry-exporter-otlp==1.38.0
      - opentelemetry-exporter-otlp-proto-http==1.38.0
      - ply==3.11
      - primp==0.15.0
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydantic-settings==2.12.0
      - pydub==0.25.1
      - pystache==0.6.8
      - ruff==0.14.4
      - s3transfer==0.14.0
      - safehttpx==0.1.7
      - semantic-version==2.10.0
      - sigtools==4.0.1
      - smolagents==1.22.0
      - socksio==1.0.0
      - soundfile==0.13.1
      - sqlalchemy==2.0.44
      - sqlean-py==3.50.4.5
      - sse-starlette==3.0.3
      - strawberry-graphql==0.270.1
      - synchronicity==0.10.2
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomlkit==0.13.3
      - transformers==4.57.1
      - types-certifi==2021.10.8.3
      - types-toml==0.10.8.20240310
      - wcmatch==10.1
prefix: /home/roberto/anaconda3/envs/deepresearch
